export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const FETCH_ARTICLES_SUCCEEDED = 'FETCH_ARTICLES_SUCCEEDED';
export const FETCH_ARTICLES_FAILED = 'FETCH_ARTICLES_FAILED';
export const FETCH_PAGING = 'FETCH_PAGING';

export const EDITOR_ARTICLE = 'EDITOR_ARTICLE';
// export const EDIT_ARTICLE = 'EDIT_ARTICLE';
export const EDITOR_ARTICLE_SUCCEEDED  = 'EDITOR_ARTICLE_SUCCEEDED';
export const EDITOR_ARTICLE_FAILED  = 'EDITOR_ARTICLE_FAILED';

export const FETCH_ARTICLE = 'FETCH_ARTICLE';
export const FETCH_ARTICLE_SUCCEEDED = 'FETCH_ARTICLE_SUCCEEDED';
export const FETCH_ARTICLE_FAILED = 'FETCH_ARTICLE_FAILED';

export const FETCH_SUCCEEDED = 'FETCH_SUCCEEDED';
export const FETCH_FAILED = 'FETCH_FAILED';

export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';


export const FETCH_PROFILE = 'FETCH_PROFILE';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAILED = 'FETCH_PROFILE_FAILED';

export const EDIT_PROFILE = 'EDIT_PROFILE';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILED = 'FETCH_PROFILE_FAILED';

export const FETCH_TAGS_SUCCEEDED = 'FETCH_TAGS_SUCCEEDED';
export const FETCH_TAGS_FAILED = 'FETCH_TAGS_FAILED';

